name = "vibe-pub"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "vibe-pub"
database_id = "48965b82-002e-41c6-83ca-fab466131c3a"

# R2 disabled until enabled in Cloudflare dashboard
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "vibe-pub"

[vars]
RESEND_FROM = "noreply@vibe.pub"
BASE_URL = "https://vibe-pub.pages.dev"
GITHUB_CLIENT_ID = "Ov23li07dxuZdYvSBwyd"
GOOGLE_CLIENT_ID = "405921837588-t5bno9do1bach6c50gg47bsgrt1vk2q2.apps.googleusercontent.com"
